import type { RequestHandler } from "express";
export declare const adminController: {
    getDashboard: RequestHandler;
    listProducts: RequestHandler;
    deleteProduct: RequestHandler;
    listOrders: RequestHandler;
    updateOrderStatus: RequestHandler;
    listUsers: RequestHandler;
    updateUserRole: RequestHandler;
    updateUserTier: RequestHandler;
    listPendingReviews: RequestHandler;
    listBrands: RequestHandler;
    createBrand: RequestHandler;
    updateBrand: RequestHandler;
    deleteBrand: RequestHandler;
    listCollections: RequestHandler;
    createCollection: RequestHandler;
    updateCollection: RequestHandler;
    deleteCollection: RequestHandler;
    getNewsletterStats: RequestHandler;
    listCoupons: RequestHandler;
    createCoupon: RequestHandler;
    updateCoupon: RequestHandler;
    deleteCoupon: RequestHandler;
    getUser: RequestHandler;
    deleteUser: RequestHandler;
    listNewsletterSubscribers: RequestHandler;
    listCategories: RequestHandler;
    createCategory: RequestHandler;
    updateCategory: RequestHandler;
    deleteCategory: RequestHandler;
};
//# sourceMappingURL=admin.controller.d.ts.map