import { Prisma } from "@prisma/client";
export declare const orderRepo: {
    findById(id: string): Prisma.Prisma__OrderClient<({
        items: {
            id: string;
            createdAt: Date;
            orderId: string;
            currencyCode: string;
            productId: string | null;
            title: string;
            variantId: string | null;
            variantName: string | null;
            unitPrice: number;
            quantity: number;
            lineTotal: number;
            imageUrl: string | null;
            position: number;
        }[];
        payments: {
            status: import("@prisma/client").$Enums.PaymentStatus;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            orderId: string;
            currencyCode: string;
            method: import("@prisma/client").$Enums.PaymentMethod;
            amount: number;
            authority: string | null;
            transactionRef: string | null;
            paidAt: Date | null;
        }[];
    } & {
        status: import("@prisma/client").$Enums.OrderStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        userId: string | null;
        orderNumber: string;
        shippingMethod: import("@prisma/client").$Enums.ShippingMethod;
        paymentMethod: import("@prisma/client").$Enums.PaymentMethod;
        couponCode: string | null;
        giftWrap: boolean;
        note: string | null;
        subtotal: number;
        discountTotal: number;
        shippingTotal: number;
        giftWrapTotal: number;
        total: number;
        currencyCode: string;
        shippingFirstName: string;
        shippingLastName: string;
        shippingPhone: string;
        shippingPostalCode: string | null;
        shippingProvince: string;
        shippingCity: string;
        shippingAddressLine1: string;
        shippingAddressLine2: string | null;
        shippingCountry: string;
        placedAt: Date;
    }) | null, null, import("@prisma/client/runtime/library").DefaultArgs, {
        log: any;
    }>;
    findByNumber(orderNumber: string): Prisma.Prisma__OrderClient<({
        items: {
            id: string;
            createdAt: Date;
            orderId: string;
            currencyCode: string;
            productId: string | null;
            title: string;
            variantId: string | null;
            variantName: string | null;
            unitPrice: number;
            quantity: number;
            lineTotal: number;
            imageUrl: string | null;
            position: number;
        }[];
        payments: {
            status: import("@prisma/client").$Enums.PaymentStatus;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            orderId: string;
            currencyCode: string;
            method: import("@prisma/client").$Enums.PaymentMethod;
            amount: number;
            authority: string | null;
            transactionRef: string | null;
            paidAt: Date | null;
        }[];
    } & {
        status: import("@prisma/client").$Enums.OrderStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        userId: string | null;
        orderNumber: string;
        shippingMethod: import("@prisma/client").$Enums.ShippingMethod;
        paymentMethod: import("@prisma/client").$Enums.PaymentMethod;
        couponCode: string | null;
        giftWrap: boolean;
        note: string | null;
        subtotal: number;
        discountTotal: number;
        shippingTotal: number;
        giftWrapTotal: number;
        total: number;
        currencyCode: string;
        shippingFirstName: string;
        shippingLastName: string;
        shippingPhone: string;
        shippingPostalCode: string | null;
        shippingProvince: string;
        shippingCity: string;
        shippingAddressLine1: string;
        shippingAddressLine2: string | null;
        shippingCountry: string;
        placedAt: Date;
    }) | null, null, import("@prisma/client/runtime/library").DefaultArgs, {
        log: any;
    }>;
    findForUser(id: string, userId: string): Prisma.Prisma__OrderClient<({
        items: {
            id: string;
            createdAt: Date;
            orderId: string;
            currencyCode: string;
            productId: string | null;
            title: string;
            variantId: string | null;
            variantName: string | null;
            unitPrice: number;
            quantity: number;
            lineTotal: number;
            imageUrl: string | null;
            position: number;
        }[];
        payments: {
            status: import("@prisma/client").$Enums.PaymentStatus;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            orderId: string;
            currencyCode: string;
            method: import("@prisma/client").$Enums.PaymentMethod;
            amount: number;
            authority: string | null;
            transactionRef: string | null;
            paidAt: Date | null;
        }[];
    } & {
        status: import("@prisma/client").$Enums.OrderStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        userId: string | null;
        orderNumber: string;
        shippingMethod: import("@prisma/client").$Enums.ShippingMethod;
        paymentMethod: import("@prisma/client").$Enums.PaymentMethod;
        couponCode: string | null;
        giftWrap: boolean;
        note: string | null;
        subtotal: number;
        discountTotal: number;
        shippingTotal: number;
        giftWrapTotal: number;
        total: number;
        currencyCode: string;
        shippingFirstName: string;
        shippingLastName: string;
        shippingPhone: string;
        shippingPostalCode: string | null;
        shippingProvince: string;
        shippingCity: string;
        shippingAddressLine1: string;
        shippingAddressLine2: string | null;
        shippingCountry: string;
        placedAt: Date;
    }) | null, null, import("@prisma/client/runtime/library").DefaultArgs, {
        log: any;
    }>;
    count(where?: any): Prisma.PrismaPromise<number>;
    list(where: any, page?: number, perPage?: number): Prisma.PrismaPromise<{
        status: import("@prisma/client").$Enums.OrderStatus;
        id: string;
        orderNumber: string;
        total: number;
        currencyCode: string;
        placedAt: Date;
        _count: {
            items: number;
        };
    }[]>;
    create(data: any, items?: Array<any>, payment?: any): Promise<any>;
    updateStatus(id: string, status: NonNullable<any>): Prisma.Prisma__OrderClient<{
        status: import("@prisma/client").$Enums.OrderStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        userId: string | null;
        orderNumber: string;
        shippingMethod: import("@prisma/client").$Enums.ShippingMethod;
        paymentMethod: import("@prisma/client").$Enums.PaymentMethod;
        couponCode: string | null;
        giftWrap: boolean;
        note: string | null;
        subtotal: number;
        discountTotal: number;
        shippingTotal: number;
        giftWrapTotal: number;
        total: number;
        currencyCode: string;
        shippingFirstName: string;
        shippingLastName: string;
        shippingPhone: string;
        shippingPostalCode: string | null;
        shippingProvince: string;
        shippingCity: string;
        shippingAddressLine1: string;
        shippingAddressLine2: string | null;
        shippingCountry: string;
        placedAt: Date;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, {
        log: any;
    }>;
    createPayment(orderId: string, data: any): Prisma.Prisma__PaymentClient<{
        status: import("@prisma/client").$Enums.PaymentStatus;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        orderId: string;
        currencyCode: string;
        method: import("@prisma/client").$Enums.PaymentMethod;
        amount: number;
        authority: string | null;
        transactionRef: string | null;
        paidAt: Date | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, {
        log: any;
    }>;
    listItems(orderId: string): Prisma.PrismaPromise<{
        id: string;
        createdAt: Date;
        orderId: string;
        currencyCode: string;
        productId: string | null;
        title: string;
        variantId: string | null;
        variantName: string | null;
        unitPrice: number;
        quantity: number;
        lineTotal: number;
        imageUrl: string | null;
        position: number;
    }[]>;
};
export default orderRepo;
//# sourceMappingURL=order.repo.d.ts.map