declare const env: {
    isDev: boolean;
    isProd: boolean;
    corsOrigins: string[];
    cookieSecure: boolean;
    prismaLogQueries: boolean;
    smtpSecure: boolean;
    inventoryBackorder: boolean;
    taxEnabled: boolean;
    taxInclusivePrices: boolean;
    taxShipping: boolean;
    pricingEnableSampleCoupons: boolean;
    rateLimit: {
        windowMs: number;
        max: number;
    };
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    APP_NAME: string;
    JSON_LIMIT: string;
    JWT_ACCESS_EXPIRES_IN: string;
    JWT_REFRESH_EXPIRES_IN: string;
    ACCESS_TOKEN_COOKIE_NAME: string;
    REFRESH_TOKEN_COOKIE_NAME: string;
    COOKIE_PATH: string;
    CURRENCY_DEFAULT: string;
    TAX_COUNTRY_DEFAULT: string;
    APP_URL?: string | undefined;
    CORS_ALLOWED_ORIGINS?: string | undefined;
    PRISMA_LOG_QUERIES?: string | undefined;
    REDIS_URL?: string | undefined;
    REDIS_HOST?: string | undefined;
    REDIS_PORT?: number | undefined;
    REDIS_PASSWORD?: string | undefined;
    REDIS_DB?: number | undefined;
    REDIS_TLS?: string | undefined;
    JWT_SECRET?: string | undefined;
    JWT_ACCESS_SECRET?: string | undefined;
    JWT_REFRESH_SECRET?: string | undefined;
    COOKIE_DOMAIN?: string | undefined;
    COOKIE_SECURE?: string | undefined;
    COOKIE_SAME_SITE?: "lax" | "strict" | "none" | undefined;
    AUTH_OTP_DIGITS?: number | undefined;
    AUTH_OTP_TTL_SEC?: number | undefined;
    AUTH_OTP_MAX_ATTEMPTS?: number | undefined;
    AUTH_OTP_RESEND_DELAY_SEC?: number | undefined;
    AUTH_OTP_SEND_LIMIT_WINDOW_SEC?: number | undefined;
    AUTH_OTP_SEND_LIMIT_PER_PHONE?: number | undefined;
    AUTH_OTP_SEND_LIMIT_PER_IP?: number | undefined;
    RECAPTCHA_SECRET?: string | undefined;
    PRICING_FREE_SHIP_THRESHOLD?: number | undefined;
    PRICING_BASE_SHIPPING?: number | undefined;
    PRICING_EXPRESS_SURCHARGE?: number | undefined;
    PRICING_GIFT_WRAP_PRICE?: number | undefined;
    PRICING_ENABLE_SAMPLE_COUPONS?: string | undefined;
    INVENTORY_ALLOW_BACKORDER?: string | undefined;
    TAX_ENABLED?: string | undefined;
    TAX_RATE_PERCENT?: number | undefined;
    TAX_INCLUSIVE_PRICES?: string | undefined;
    TAX_TAXABLE_SHIPPING?: string | undefined;
    TAX_REGION_OVERRIDES?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASS?: string | undefined;
    SMTP_SECURE?: string | undefined;
    MAIL_FROM?: string | undefined;
    QUEUE_EMAIL_CONCURRENCY?: number | undefined;
    PAYMENT_PROVIDER?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    PAYPAL_CLIENT_ID?: string | undefined;
    PAYPAL_SECRET?: string | undefined;
    PAYPAL_ENV?: string | undefined;
    S3_REGION?: string | undefined;
    S3_ENDPOINT?: string | undefined;
    S3_FORCE_PATH_STYLE?: string | undefined;
    S3_ACCESS_KEY?: string | undefined;
    S3_SECRET_KEY?: string | undefined;
    ELASTICSEARCH_NODE?: string | undefined;
    ELASTICSEARCH_USERNAME?: string | undefined;
    ELASTICSEARCH_PASSWORD?: string | undefined;
    ELASTICSEARCH_TLS_REJECT_UNAUTHORIZED?: string | undefined;
    RATE_LIMIT_WINDOW_MS?: number | undefined;
    RATE_LIMIT_MAX?: number | undefined;
};
export type Env = typeof env;
export { env };
export default env;
//# sourceMappingURL=env.d.ts.map